---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: CustomizeRequest_miq_bu1
    inherits: 
    description: 
  fields:
  - execute:
      value: CustomizeRequest_miq_bu1
